Algoritmo "lista de exercicio(ex2)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/08/2024
Var
// Seção de Declarações das variáveis 
a:inteiro
d:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Seleciona um numero")
leia(a)
d<-a*2
escreva("o dobro: ",d)



Fimalgoritmo